---

# exemplo de uso de variaveis ( ver defaults/main.yml)
- name: dar um ls em um diretorio qualquer
  command: ls -la {{item}}
  with_items:
    - "{{ folders_list }}"

- name: fazer os updates do suse
  community.general.zypper:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_distribution == 'openSUSE Leap' #poderia ter um or ou o que seja na condicao #lembrando que as variaveis podem ser obtidas via modulo setup

- name: fazer os updates do ubuntu
  apt:
    upgrade: "yes"
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' #poderia ter um or ou o que seja na condicao

# quando voce tem arquivos em files no seu role pode usar copy conforme o exemplo abaixo para copia-los para a maquina de destino de

#- name: copia de arquivos
#  copy:  src=arquivo.txt dest=/tmp/arquivo.txt


# quando voce tem arquivos em templates no seu role pode usar template conforme o exemplo abaixo para copia-los para o destino com a interpolacao de variaveis
# dica : para consultar variaveis ansible eh possivel utilizar o modulo setup lembrando o formato de variaveis "{{ variavel }}"

#- name: copia template
#  template:  src=arquivo.txt dest=/tmp/arquivo.txt force=yes owner=root group=root


# atualizacao dos repositoriso apt
#-  name:  update apt repos
#   apt:  update_cache=yes force_apt_get=yes cache_valid_time=3600

# atualizacao dos pacotes apt
#-  name:  update apt packages
#   apt:  upgrade=dist force_apt_get=yes

# exemplo de uso de variaveis ( ver defaults/main.yml)
#- name: dar um ls em um diretorio qualquer
#  command: ls -la {{item}}
#  with_items:
#    - "{{ folders_list }}"
